# Generated by Django 2.2 on 2019-05-28 15:53

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersWithBasket',
            fields=[
            ],
            options={
                'verbose_name': 'Пользователь с корзиной',
                'verbose_name_plural': 'Пользователи с корзиной',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authapp.shopuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
